/*
 * test_solar_edge.c — Edge case tests for solar calendar boundary dates.
 *
 * Auto-generated by tools/solar_boundary_scan.c.
 * Contains the 100 closest sankrantis to each calendar's critical time
 * for Tamil, Bengali, Odia, and Malayalam calendars (1900-2050).
 *
 * Initially populated with OUR code's predictions. User verifies against
 * drikpanchang.com and updates exp values where our code disagrees.
 */

#include "solar.h"
#include "astro.h"
#include "date_utils.h"
#include <stdio.h>
#include <string.h>
#include <math.h>

static int tests_run = 0;
static int tests_passed = 0;
static int tests_failed = 0;

static void check(int condition, const char *msg)
{
    tests_run++;
    if (condition) {
        tests_passed++;
    } else {
        tests_failed++;
        printf("  FAIL: %s\n", msg);
    }
}

/*
 * Edge case reference data: 100 closest sankrantis per calendar.
 * Each entry tests the first day of the new solar month.
 *
 * Fields:
 *   gy, gm, gd     — Gregorian date of our computed day 1
 *   type            — Solar calendar type
 *   exp_month       — Expected regional month number
 *   exp_day         — Expected day (should be 1)
 *   exp_year        — Expected regional era year
 *
 * The comment on each line shows delta (minutes from critical time),
 * sankranti IST, and critical time IST.
 */
static struct {
    int gy, gm, gd;
    SolarCalendarType type;
    int exp_month;
    int exp_day;
    int exp_year;
} edge_cases[] = {

    /* ---- TAMIL - 100 closest to sunset ---- */
    {1962,  2, 12, SOLAR_CAL_TAMIL,       10, 30, 1883},  /* delta=-0.2min sank=18:07:30 crit=18:07:41 rashi=11 CORRECTED */
    {1949,  6, 15, SOLAR_CAL_TAMIL,        3, 1, 1871},  /* delta=+1.1min sank=19:19:42 crit=19:18:36 rashi=3 */
    {1969,  4, 13, SOLAR_CAL_TAMIL,       12, 31, 1890},  /* delta=-2.1min sank=18:42:28 crit=18:44:34 rashi=1 CORRECTED */
    {1910,  6, 15, SOLAR_CAL_TAMIL,        3, 1, 1832},  /* delta=+3.4min sank=19:21:48 crit=19:18:21 rashi=3 */
    {1977,  9, 17, SOLAR_CAL_TAMIL,        6, 1, 1899},  /* delta=+3.5min sank=18:27:51 crit=18:24:24 rashi=6 */
    {1971, 11, 16, SOLAR_CAL_TAMIL,        7, 31, 1893},  /* delta=-4.5min sank=17:21:52 crit=17:26:24 rashi=8 CORRECTED */
    {2032,  5, 14, SOLAR_CAL_TAMIL,        1, 31, 1954},  /* delta=-4.7min sank=18:58:47 crit=19:03:27 rashi=2 CORRECTED */
    {2037,  7, 17, SOLAR_CAL_TAMIL,        4, 1, 1959},  /* delta=+6.3min sank=19:25:38 crit=19:19:20 rashi=4 */
    {1915,  5, 15, SOLAR_CAL_TAMIL,        2, 1, 1837},  /* delta=+6.8min sank=19:09:09 crit=19:02:18 rashi=2 */
    {1930,  4, 14, SOLAR_CAL_TAMIL,        1, 1, 1852},  /* delta=+7.2min sank=18:51:25 crit=18:44:14 rashi=1 */
    {1923,  2, 12, SOLAR_CAL_TAMIL,       10, 30, 1844},  /* delta=-7.4min sank=17:59:55 crit=18:07:21 rashi=11 CORRECTED */
    {1964,  1, 14, SOLAR_CAL_TAMIL,        9, 30, 1885},  /* delta=-7.7min sank=17:35:54 crit=17:43:36 rashi=10 CORRECTED */
    {2040,  2, 14, SOLAR_CAL_TAMIL,       11, 1, 1961},  /* delta=+8.4min sank=18:16:43 crit=18:08:21 rashi=11 */
    {2031,  6, 16, SOLAR_CAL_TAMIL,        3, 1, 1953},  /* delta=+8.4min sank=19:27:36 crit=19:19:09 rashi=3 */
    {1998,  7, 17, SOLAR_CAL_TAMIL,        4, 1, 1920},  /* delta=+8.5min sank=19:28:00 crit=19:19:28 rashi=4 */
    {1932, 11, 15, SOLAR_CAL_TAMIL,        8, 1, 1854},  /* delta=-8.7min sank=17:18:02 crit=17:26:42 rashi=8 */
    {2042,  1, 14, SOLAR_CAL_TAMIL,       10, 1, 1963},  /* delta=-9.3min sank=17:35:01 crit=17:44:19 rashi=10 */
    {1993,  5, 15, SOLAR_CAL_TAMIL,        2, 1, 1915},  /* delta=+9.4min sank=19:12:27 crit=19:03:02 rashi=2 */
    {2049, 11, 16, SOLAR_CAL_TAMIL,        8, 1, 1971},  /* delta=-10.0min sank=17:15:54 crit=17:25:53 rashi=8 */
    {1959,  7, 17, SOLAR_CAL_TAMIL,        4, 1, 1881},  /* delta=+10.7min sank=19:30:19 crit=19:19:35 rashi=4 */
    {2003,  1, 14, SOLAR_CAL_TAMIL,       10, 1, 1924},  /* delta=-11.0min sank=17:33:00 crit=17:43:58 rashi=10 */
    {2047,  4, 14, SOLAR_CAL_TAMIL,        1, 1, 1969},  /* delta=-11.0min sank=18:34:12 crit=18:45:13 rashi=1 */
    {1971, 10, 17, SOLAR_CAL_TAMIL,        7, 1, 1893},  /* delta=-11.3min sank=17:38:02 crit=17:49:22 rashi=7 */
    {1982,  3, 14, SOLAR_CAL_TAMIL,       12, 1, 1903},  /* delta=-11.5min sank=18:16:11 crit=18:27:42 rashi=12 */
    {1932, 10, 16, SOLAR_CAL_TAMIL,        7, 1, 1854},  /* delta=-11.7min sank=17:38:17 crit=17:49:57 rashi=7 */
    {2001,  2, 13, SOLAR_CAL_TAMIL,       11, 1, 1922},  /* delta=+12.0min sank=18:20:01 crit=18:08:00 rashi=11 */
    {1938,  8, 16, SOLAR_CAL_TAMIL,        5, 1, 1860},  /* delta=-12.3min sank=18:46:57 crit=18:59:14 rashi=5 */
    {1911,  5, 14, SOLAR_CAL_TAMIL,        2, 1, 1833},  /* delta=-12.8min sank=18:49:29 crit=19:02:15 rashi=2 */
    {1918, 12, 16, SOLAR_CAL_TAMIL,        9, 1, 1840},  /* delta=+13.9min sank=17:38:52 crit=17:25:00 rashi=9 */
    {1954,  5, 15, SOLAR_CAL_TAMIL,        2, 1, 1876},  /* delta=+14.0min sank=19:16:41 crit=19:02:39 rashi=2 */
    {2016,  9, 17, SOLAR_CAL_TAMIL,        6, 1, 1938},  /* delta=+14.3min sank=18:37:59 crit=18:23:44 rashi=6 */
    {1938,  9, 17, SOLAR_CAL_TAMIL,        6, 1, 1860},  /* delta=+14.4min sank=18:39:27 crit=18:25:01 rashi=6 */
    {2010, 11, 16, SOLAR_CAL_TAMIL,        8, 1, 1932},  /* delta=-14.8min sank=17:11:20 crit=17:26:09 rashi=8 */
    {1975, 10, 18, SOLAR_CAL_TAMIL,        7, 1, 1897},  /* delta=+15.8min sank=18:05:11 crit=17:49:21 rashi=7 */
    {2016,  8, 16, SOLAR_CAL_TAMIL,        5, 1, 1938},  /* delta=-16.4min sank=18:41:50 crit=18:58:16 rashi=5 */
    {2031, 12, 16, SOLAR_CAL_TAMIL,        9, 1, 1953},  /* delta=-16.5min sank=17:08:53 crit=17:25:22 rashi=9 */
    {1914, 12, 15, SOLAR_CAL_TAMIL,        9, 1, 1836},  /* delta=-16.9min sank=17:08:04 crit=17:24:59 rashi=9 */
    {1957, 12, 16, SOLAR_CAL_TAMIL,        9, 1, 1879},  /* delta=+16.9min sank=17:42:04 crit=17:25:07 rashi=9 */
    {1973,  4, 14, SOLAR_CAL_TAMIL,        1, 1, 1895},  /* delta=+17.0min sank=19:01:37 crit=18:44:38 rashi=1 */
    {1992,  6, 15, SOLAR_CAL_TAMIL,        3, 1, 1914},  /* delta=+17.0min sank=19:35:55 crit=19:18:54 rashi=3 */
    {1908,  3, 14, SOLAR_CAL_TAMIL,       12, 1, 1829},  /* delta=+17.0min sank=18:44:11 crit=18:27:10 rashi=12 */
    {1986,  3, 15, SOLAR_CAL_TAMIL,       12, 1, 1907},  /* delta=+17.3min sank=18:45:02 crit=18:27:43 rashi=12 */
    {1943,  3, 14, SOLAR_CAL_TAMIL,       12, 1, 1864},  /* delta=-17.3min sank=18:10:04 crit=18:27:25 rashi=12 */
    {2021,  3, 14, SOLAR_CAL_TAMIL,       12, 1, 1942},  /* delta=-18.0min sank=18:10:02 crit=18:28:00 rashi=12 */
    {1947,  3, 15, SOLAR_CAL_TAMIL,       12, 1, 1868},  /* delta=+18.3min sank=18:45:44 crit=18:27:26 rashi=12 */
    {1916,  7, 15, SOLAR_CAL_TAMIL,        4, 1, 1838},  /* delta=-18.6min sank=19:01:08 crit=19:19:42 rashi=4 */
    {1968,  1, 15, SOLAR_CAL_TAMIL,       10, 1, 1889},  /* delta=+19.1min sank=18:02:46 crit=17:43:38 rashi=10 */
    {1988,  6, 14, SOLAR_CAL_TAMIL,        3, 1, 1910},  /* delta=-19.2min sank=18:59:42 crit=19:18:54 rashi=3 */
    {1992, 12, 15, SOLAR_CAL_TAMIL,        9, 1, 1914},  /* delta=-19.6min sank=17:05:37 crit=17:25:14 rashi=9 */
    {2008,  4, 13, SOLAR_CAL_TAMIL,        1, 1, 1930},  /* delta=-19.7min sank=18:25:17 crit=18:44:56 rashi=1 */
    {2014, 10, 18, SOLAR_CAL_TAMIL,        7, 1, 1936},  /* delta=+19.7min sank=18:08:28 crit=17:48:47 rashi=7 */
    {2020,  8, 17, SOLAR_CAL_TAMIL,        5, 1, 1942},  /* delta=+19.7min sank=19:18:00 crit=18:58:15 rashi=5 */
    {1929,  1, 14, SOLAR_CAL_TAMIL,       10, 1, 1850},  /* delta=+20.3min sank=18:03:38 crit=17:43:17 rashi=10 */
    {1996, 12, 16, SOLAR_CAL_TAMIL,        9, 1, 1918},  /* delta=+20.7min sank=17:45:58 crit=17:25:15 rashi=9 */
    {1942,  8, 17, SOLAR_CAL_TAMIL,        5, 1, 1864},  /* delta=+21.2min sank=19:20:27 crit=18:59:14 rashi=5 */
    {1925,  1, 13, SOLAR_CAL_TAMIL,       10, 1, 1846},  /* delta=-21.3min sank=17:22:02 crit=17:43:17 rashi=10 */
    {1906,  6, 14, SOLAR_CAL_TAMIL,        3, 1, 1828},  /* delta=-22.0min sank=18:56:18 crit=19:18:18 rashi=3 */
    {2007,  1, 15, SOLAR_CAL_TAMIL,       10, 1, 1928},  /* delta=+22.1min sank=18:06:06 crit=17:43:59 rashi=10 */
    {2025,  3, 15, SOLAR_CAL_TAMIL,       12, 1, 1946},  /* delta=+22.2min sank=18:50:12 crit=18:27:59 rashi=12 */
    {2046,  1, 15, SOLAR_CAL_TAMIL,       10, 1, 1967},  /* delta=+23.2min sank=18:07:30 crit=17:44:20 rashi=10 */
    {1950,  5, 14, SOLAR_CAL_TAMIL,        2, 1, 1872},  /* delta=-23.2min sank=18:39:24 crit=19:02:39 rashi=2 */
    {1977,  8, 16, SOLAR_CAL_TAMIL,        5, 1, 1899},  /* delta=-23.9min sank=18:34:52 crit=18:58:46 rashi=5 */
    {2036,  2, 13, SOLAR_CAL_TAMIL,       11, 1, 1957},  /* delta=-24.6min sank=17:43:42 crit=18:08:19 rashi=11 */
    {1953,  6, 15, SOLAR_CAL_TAMIL,        3, 1, 1875},  /* delta=+24.9min sank=19:43:31 crit=19:18:38 rashi=3 */
    {1975, 11, 17, SOLAR_CAL_TAMIL,        8, 1, 1897},  /* delta=+25.0min sank=17:51:23 crit=17:26:25 rashi=8 */
    {1953, 12, 15, SOLAR_CAL_TAMIL,        9, 1, 1875},  /* delta=-25.1min sank=16:59:59 crit=17:25:07 rashi=9 */
    {1904,  3, 13, SOLAR_CAL_TAMIL,       12, 1, 1825},  /* delta=-25.3min sank=18:01:51 crit=18:27:09 rashi=12 */
    {1920,  7, 16, SOLAR_CAL_TAMIL,        4, 1, 1842},  /* delta=+25.3min sank=19:44:59 crit=19:19:40 rashi=4 */
    {2049, 10, 17, SOLAR_CAL_TAMIL,        7, 1, 1971},  /* delta=-26.1min sank=17:22:07 crit=17:48:15 rashi=7 */
    {1936, 10, 17, SOLAR_CAL_TAMIL,        7, 1, 1858},  /* delta=+26.6min sank=18:16:28 crit=17:49:54 rashi=7 */
    {1955,  7, 16, SOLAR_CAL_TAMIL,        4, 1, 1877},  /* delta=-26.7min sank=18:52:54 crit=19:19:35 rashi=4 */
    {1934,  9, 16, SOLAR_CAL_TAMIL,        6, 1, 1856},  /* delta=-27.0min sank=17:58:02 crit=18:25:04 rashi=6 */
    {1973,  9, 16, SOLAR_CAL_TAMIL,        6, 1, 1895},  /* delta=-27.1min sank=17:57:18 crit=18:24:24 rashi=6 */
    {1989,  5, 14, SOLAR_CAL_TAMIL,        2, 1, 1911},  /* delta=-27.3min sank=18:35:41 crit=19:03:01 rashi=2 */
    {2010, 10, 17, SOLAR_CAL_TAMIL,        7, 1, 1932},  /* delta=-28.0min sank=17:20:49 crit=17:48:49 rashi=7 */
    {2027,  6, 15, SOLAR_CAL_TAMIL,        3, 1, 1949},  /* delta=-28.1min sank=18:51:01 crit=19:19:09 rashi=3 */
    {2012,  4, 14, SOLAR_CAL_TAMIL,        1, 1, 1934},  /* delta=+28.4min sank=19:13:20 crit=18:44:55 rashi=1 */
    {1936, 11, 16, SOLAR_CAL_TAMIL,        8, 1, 1858},  /* delta=+29.5min sank=17:56:09 crit=17:26:41 rashi=8 */
    {1934,  4, 14, SOLAR_CAL_TAMIL,        1, 1, 1856},  /* delta=+29.8min sank=19:14:05 crit=18:44:17 rashi=1 */
    {1965,  4, 13, SOLAR_CAL_TAMIL,        1, 1, 1887},  /* delta=-32.1min sank=18:12:29 crit=18:44:33 rashi=1 */
    {2028,  5, 14, SOLAR_CAL_TAMIL,        2, 1, 1950},  /* delta=-32.6min sank=18:30:45 crit=19:03:24 rashi=2 */
    {1945,  6, 14, SOLAR_CAL_TAMIL,        3, 1, 1867},  /* delta=-33.4min sank=18:45:11 crit=19:18:35 rashi=3 */
    {2014, 11, 17, SOLAR_CAL_TAMIL,        8, 1, 1936},  /* delta=+33.5min sank=17:59:40 crit=17:26:08 rashi=8 */
    {1981,  8, 17, SOLAR_CAL_TAMIL,        5, 1, 1903},  /* delta=+34.0min sank=19:32:46 crit=18:58:43 rashi=5 */
    {2035, 12, 17, SOLAR_CAL_TAMIL,        9, 1, 1957},  /* delta=+34.1min sank=17:59:29 crit=17:25:21 rashi=9 */
    {1994,  7, 16, SOLAR_CAL_TAMIL,        4, 1, 1916},  /* delta=-34.6min sank=18:44:54 crit=19:19:28 rashi=4 */
    {1903,  8, 17, SOLAR_CAL_TAMIL,        5, 1, 1825},  /* delta=+35.1min sank=19:34:45 crit=18:59:41 rashi=5 */
    {2012,  9, 16, SOLAR_CAL_TAMIL,        6, 1, 1934},  /* delta=-35.5min sank=17:48:17 crit=18:23:46 rashi=6 */
    {1928, 11, 15, SOLAR_CAL_TAMIL,        8, 1, 1850},  /* delta=-36.0min sank=16:50:44 crit=17:26:43 rashi=8 */
    {2044,  2, 14, SOLAR_CAL_TAMIL,       11, 1, 1965},  /* delta=+36.2min sank=18:44:35 crit=18:08:23 rashi=11 */
    {2005,  2, 13, SOLAR_CAL_TAMIL,       11, 1, 1926},  /* delta=+36.9min sank=18:44:58 crit=18:08:03 rashi=11 */
    {2004,  4, 13, SOLAR_CAL_TAMIL,        1, 1, 1926},  /* delta=-37.7min sank=18:07:10 crit=18:44:53 rashi=1 */
    {1914,  6, 15, SOLAR_CAL_TAMIL,        3, 1, 1836},  /* delta=+38.3min sank=19:56:38 crit=19:18:22 rashi=3 */
    {2033,  7, 16, SOLAR_CAL_TAMIL,        4, 1, 1955},  /* delta=-38.3min sank=18:41:03 crit=19:19:20 rashi=4 */
    {1928, 10, 16, SOLAR_CAL_TAMIL,        7, 1, 1850},  /* delta=-39.5min sank=17:10:28 crit=17:49:59 rashi=7 */
    {1999,  1, 14, SOLAR_CAL_TAMIL,       10, 1, 1920},  /* delta=-39.7min sank=17:04:15 crit=17:43:56 rashi=10 */
    {1967, 11, 16, SOLAR_CAL_TAMIL,        8, 1, 1889},  /* delta=-39.8min sank=16:46:40 crit=17:26:26 rashi=8 */
    {1926,  4, 13, SOLAR_CAL_TAMIL,        1, 1, 1848},  /* delta=-40.0min sank=18:04:18 crit=18:44:15 rashi=1 */
    {1927,  2, 13, SOLAR_CAL_TAMIL,       11, 1, 1848},  /* delta=+40.7min sank=18:48:04 crit=18:07:21 rashi=11 */
    {2006, 11, 16, SOLAR_CAL_TAMIL,        8, 1, 1928},  /* delta=-41.0min sank=16:45:08 crit=17:26:09 rashi=8 */

    /* ---- BENGALI - 100 closest to midnight+24min ---- */
    {1963,  2, 13, SOLAR_CAL_BENGALI,     11, 1, 1369},  /* delta=-0.1min sank=00:23:53 crit=00:23:59 rashi=11 */
    {1908,  5, 14, SOLAR_CAL_BENGALI,      2, 1, 1315},  /* delta=-0.2min sank=00:23:49 crit=00:23:59 rashi=2 */
    {1976, 10, 17, SOLAR_CAL_BENGALI,      7, 1, 1383},  /* delta=-0.7min sank=00:23:17 crit=00:23:59 rashi=7 */
    {1966,  4, 15, SOLAR_CAL_BENGALI,      1, 1, 1373},  /* delta=+0.8min sank=00:24:49 crit=00:23:59 rashi=1 */
    {2041,  2, 14, SOLAR_CAL_BENGALI,     11, 1, 1447},  /* delta=+1.1min sank=00:25:07 crit=00:23:59 rashi=11 */
    {2022,  3, 15, SOLAR_CAL_BENGALI,     12, 1, 1428},  /* delta=-2.2min sank=00:21:50 crit=00:23:59 rashi=12 */
    {1983,  3, 15, SOLAR_CAL_BENGALI,     12, 1, 1389},  /* delta=-2.3min sank=00:21:39 crit=00:23:59 rashi=12 */
    {2047,  1, 15, SOLAR_CAL_BENGALI,     10, 1, 1453},  /* delta=-2.8min sank=00:21:14 crit=00:23:59 rashi=10 */
    {2002,  2, 14, SOLAR_CAL_BENGALI,     11, 1, 1408},  /* delta=+4.1min sank=00:28:03 crit=00:23:59 rashi=11 */
    {1909,  7, 16, SOLAR_CAL_BENGALI,      4, 1, 1316},  /* delta=-4.3min sank=00:19:40 crit=00:23:59 rashi=4 */
    {1935,  8, 17, SOLAR_CAL_BENGALI,      5, 1, 1342},  /* delta=-4.4min sank=00:19:33 crit=00:23:59 rashi=5 */
    {2024,  6, 16, SOLAR_CAL_BENGALI,      3, 1, 1431},  /* delta=+4.9min sank=00:28:55 crit=00:23:59 rashi=3 */
    {1937, 10, 17, SOLAR_CAL_BENGALI,      7, 1, 1344},  /* delta=-5.2min sank=00:18:50 crit=00:23:59 rashi=7 */
    {1944,  3, 14, SOLAR_CAL_BENGALI,     12, 1, 1350},  /* delta=-5.4min sank=00:18:38 crit=00:23:59 rashi=12 */
    {1947,  5, 15, SOLAR_CAL_BENGALI,      2, 1, 1354},  /* delta=-5.9min sank=00:18:06 crit=00:23:59 rashi=2 */
    {1923, 12, 17, SOLAR_CAL_BENGALI,      9, 1, 1330},  /* delta=+7.3min sank=00:31:15 crit=00:23:59 rashi=9 */
    {2015, 10, 18, SOLAR_CAL_BENGALI,      7, 1, 1422},  /* delta=-7.3min sank=00:16:42 crit=00:23:59 rashi=7 */
    {1952,  7, 17, SOLAR_CAL_BENGALI,      4, 1, 1359},  /* delta=+7.5min sank=00:31:27 crit=00:23:59 rashi=4 */
    {1927,  4, 14, SOLAR_CAL_BENGALI,      1, 1, 1334},  /* delta=-8.9min sank=00:15:06 crit=00:23:59 rashi=1 */
    {1905,  3, 14, SOLAR_CAL_BENGALI,     12, 1, 1311},  /* delta=-9.6min sank=00:14:26 crit=00:23:59 rashi=12 */
    {1935,  9, 17, SOLAR_CAL_BENGALI,      6, 1, 1342},  /* delta=-9.6min sank=00:14:25 crit=00:23:59 rashi=6 */
    {1981,  6, 15, SOLAR_CAL_BENGALI,      3, 1, 1388},  /* delta=-10.0min sank=00:14:01 crit=00:23:59 rashi=3 */
    {1991,  7, 17, SOLAR_CAL_BENGALI,      4, 1, 1398},  /* delta=-10.3min sank=00:13:40 crit=00:23:59 rashi=4 */
    {1903,  6, 15, SOLAR_CAL_BENGALI,      3, 1, 1310},  /* delta=-10.9min sank=00:13:04 crit=00:23:59 rashi=3 */
    {1969,  1, 14, SOLAR_CAL_BENGALI,     10, 1, 1375},  /* delta=-11.1min sank=00:12:53 crit=00:23:59 rashi=10 */
    {2005,  4, 14, SOLAR_CAL_BENGALI,      1, 1, 1412},  /* delta=-12.1min sank=00:11:55 crit=00:23:59 rashi=1 */
    {2025,  5, 15, SOLAR_CAL_BENGALI,      2, 1, 1432},  /* delta=-12.1min sank=00:11:52 crit=00:23:59 rashi=2 */
    {1973,  1, 15, SOLAR_CAL_BENGALI,     10, 1, 1379},  /* delta=+12.3min sank=00:36:16 crit=00:23:59 rashi=10 */
    {1930,  1, 14, SOLAR_CAL_BENGALI,     10, 1, 1336},  /* delta=-14.3min sank=00:09:43 crit=00:23:59 rashi=10 */
    {1942,  6, 15, SOLAR_CAL_BENGALI,      3, 1, 1349},  /* delta=-14.4min sank=00:09:37 crit=00:23:59 rashi=3 */
    {1986,  5, 15, SOLAR_CAL_BENGALI,      2, 1, 1393},  /* delta=-15.1min sank=00:08:51 crit=00:23:59 rashi=2 */
    {2040, 12, 17, SOLAR_CAL_BENGALI,      9, 1, 1447},  /* delta=+15.4min sank=00:39:24 crit=00:23:59 rashi=9 */
    {2029,  5, 16, SOLAR_CAL_BENGALI,      2, 1, 1436},  /* delta=+15.4min sank=00:39:26 crit=00:23:59 rashi=2 */
    {1934,  1, 15, SOLAR_CAL_BENGALI,     10, 1, 1340},  /* delta=+15.5min sank=00:39:28 crit=00:23:59 rashi=10 */
    {1976, 11, 16, SOLAR_CAL_BENGALI,      8, 1, 1383},  /* delta=-15.9min sank=00:08:07 crit=00:23:59 rashi=8 */
    {1913,  7, 17, SOLAR_CAL_BENGALI,      4, 1, 1320},  /* delta=+16.3min sank=00:40:18 crit=00:23:59 rashi=4 */
    {2030,  7, 17, SOLAR_CAL_BENGALI,      4, 1, 1437},  /* delta=-16.5min sank=00:07:29 crit=00:23:59 rashi=4 */
    {2048,  4, 15, SOLAR_CAL_BENGALI,      1, 1, 1455},  /* delta=+17.3min sank=00:41:20 crit=00:23:59 rashi=1 */
    {1978,  9, 18, SOLAR_CAL_BENGALI,      6, 1, 1385},  /* delta=+17.4min sank=00:41:21 crit=00:23:59 rashi=6 */
    {2009,  4, 15, SOLAR_CAL_BENGALI,      1, 1, 1416},  /* delta=+17.5min sank=00:41:29 crit=00:23:59 rashi=1 */
    {1924,  2, 13, SOLAR_CAL_BENGALI,     11, 1, 1330},  /* delta=-17.8min sank=00:06:12 crit=00:23:59 rashi=11 */
    {2036, 12, 16, SOLAR_CAL_BENGALI,      9, 1, 1443},  /* delta=-18.2min sank=00:05:49 crit=00:23:59 rashi=9 */
    {1951,  5, 16, SOLAR_CAL_BENGALI,      2, 1, 1358},  /* delta=+18.2min sank=00:42:13 crit=00:23:59 rashi=2 */
    {1980, 11, 17, SOLAR_CAL_BENGALI,      8, 1, 1387},  /* delta=+18.4min sank=00:42:26 crit=00:23:59 rashi=8 */
    {2001, 12, 17, SOLAR_CAL_BENGALI,      9, 1, 1408},  /* delta=+18.5min sank=00:42:29 crit=00:23:59 rashi=9 */
    {1997, 12, 16, SOLAR_CAL_BENGALI,      9, 1, 1404},  /* delta=-18.8min sank=00:05:13 crit=00:23:59 rashi=9 */
    {2008,  1, 15, SOLAR_CAL_BENGALI,     10, 1, 1414},  /* delta=-19.3min sank=00:04:40 crit=00:23:59 rashi=10 */
    {2015, 11, 17, SOLAR_CAL_BENGALI,      8, 1, 1422},  /* delta=-19.6min sank=00:04:25 crit=00:23:59 rashi=8 */
    {1962, 12, 17, SOLAR_CAL_BENGALI,      9, 1, 1369},  /* delta=+20.0min sank=00:44:02 crit=00:23:59 rashi=9 */
    {1990,  5, 16, SOLAR_CAL_BENGALI,      2, 1, 1397},  /* delta=+20.2min sank=00:44:09 crit=00:23:59 rashi=2 */
    {2044,  4, 14, SOLAR_CAL_BENGALI,      1, 1, 1451},  /* delta=-20.4min sank=00:03:38 crit=00:23:59 rashi=1 */
    {1985,  6, 16, SOLAR_CAL_BENGALI,      3, 1, 1392},  /* delta=+20.9min sank=00:44:53 crit=00:23:59 rashi=3 */
    {2017,  9, 18, SOLAR_CAL_BENGALI,      6, 1, 1424},  /* delta=+20.9min sank=00:44:55 crit=00:23:59 rashi=6 */
    {1902, 11, 17, SOLAR_CAL_BENGALI,      8, 1, 1309},  /* delta=+21.2min sank=00:45:13 crit=00:23:59 rashi=8 */
    {2013,  8, 17, SOLAR_CAL_BENGALI,      5, 1, 1420},  /* delta=-21.2min sank=00:02:45 crit=00:23:59 rashi=5 */
    {1970,  4, 15, SOLAR_CAL_BENGALI,      1, 1, 1377},  /* delta=+21.9min sank=00:45:53 crit=00:23:59 rashi=1 */
    {1974,  8, 17, SOLAR_CAL_BENGALI,      5, 1, 1381},  /* delta=-22.3min sank=00:01:40 crit=00:23:59 rashi=5 */
    {1937, 11, 16, SOLAR_CAL_BENGALI,      8, 1, 1344},  /* delta=-22.5min sank=00:01:27 crit=00:23:59 rashi=8 */
    {2020,  6, 15, SOLAR_CAL_BENGALI,      3, 1, 1427},  /* delta=-22.8min sank=00:01:12 crit=00:23:59 rashi=3 */
    {1948,  7, 16, SOLAR_CAL_BENGALI,      4, 1, 1355},  /* delta=-22.9min sank=00:01:03 crit=00:23:59 rashi=4 */
    {1939,  9, 18, SOLAR_CAL_BENGALI,      6, 1, 1346},  /* delta=+23.3min sank=00:47:20 crit=00:23:59 rashi=6 */
    {2034,  7, 18, SOLAR_CAL_BENGALI,      4, 1, 1441},  /* delta=+23.4min sank=00:47:24 crit=00:23:59 rashi=4 */
    {1978,  8, 18, SOLAR_CAL_BENGALI,      5, 1, 1385},  /* delta=+23.5min sank=00:47:31 crit=00:23:59 rashi=5 */
    {1948,  3, 15, SOLAR_CAL_BENGALI,     12, 1, 1354},  /* delta=+24.8min sank=00:48:50 crit=00:23:59 rashi=12 */
    {1941, 11, 17, SOLAR_CAL_BENGALI,      8, 1, 1348},  /* delta=+25.6min sank=00:49:33 crit=00:23:59 rashi=8 */
    {2017,  8, 18, SOLAR_CAL_BENGALI,      5, 1, 1424},  /* delta=+27.1min sank=00:51:04 crit=00:23:59 rashi=5 */
    {2012,  1, 16, SOLAR_CAL_BENGALI,     10, 1, 1418},  /* delta=+27.6min sank=00:51:33 crit=00:23:59 rashi=10 */
    {1987,  3, 16, SOLAR_CAL_BENGALI,     12, 1, 1393},  /* delta=+27.7min sank=00:51:43 crit=00:23:59 rashi=12 */
    {2051,  1, 16, SOLAR_CAL_BENGALI,     10, 1, 1457},  /* delta=+27.8min sank=00:51:48 crit=00:23:59 rashi=10 */
    {1931,  4, 15, SOLAR_CAL_BENGALI,      1, 1, 1338},  /* delta=+28.0min sank=00:52:00 crit=00:23:59 rashi=1 */
    {1939,  8, 18, SOLAR_CAL_BENGALI,      5, 1, 1346},  /* delta=+28.1min sank=00:52:04 crit=00:23:59 rashi=5 */
    {1912,  5, 15, SOLAR_CAL_BENGALI,      2, 1, 1319},  /* delta=+30.1min sank=00:54:05 crit=00:23:59 rashi=2 */
    {1907,  6, 16, SOLAR_CAL_BENGALI,      3, 1, 1314},  /* delta=+31.1min sank=00:55:05 crit=00:23:59 rashi=3 */
    {2006,  2, 14, SOLAR_CAL_BENGALI,     11, 1, 1412},  /* delta=+31.4min sank=00:55:23 crit=00:23:59 rashi=11 */
    {1909,  3, 15, SOLAR_CAL_BENGALI,     12, 1, 1315},  /* delta=+31.8min sank=00:55:45 crit=00:23:59 rashi=12 */
    {2045,  2, 14, SOLAR_CAL_BENGALI,     11, 1, 1451},  /* delta=+31.9min sank=00:55:56 crit=00:23:59 rashi=11 */
    {1995,  7, 18, SOLAR_CAL_BENGALI,      4, 1, 1402},  /* delta=+32.4min sank=00:56:24 crit=00:23:59 rashi=4 */
    {1946,  6, 16, SOLAR_CAL_BENGALI,      3, 1, 1353},  /* delta=+32.6min sank=00:56:37 crit=00:23:59 rashi=3 */
    {1928,  2, 14, SOLAR_CAL_BENGALI,     11, 1, 1334},  /* delta=+34.2min sank=00:58:12 crit=00:23:59 rashi=11 */
    {2019, 11, 18, SOLAR_CAL_BENGALI,      8, 1, 1426},  /* delta=+34.5min sank=00:58:29 crit=00:23:59 rashi=8 */
    {1967,  2, 14, SOLAR_CAL_BENGALI,     11, 1, 1373},  /* delta=+35.2min sank=00:59:14 crit=00:23:59 rashi=11 */
    {1980, 10, 18, SOLAR_CAL_BENGALI,      7, 1, 1387},  /* delta=+35.3min sank=00:59:20 crit=00:23:59 rashi=7 */
    {2026,  3, 16, SOLAR_CAL_BENGALI,     12, 1, 1432},  /* delta=+36.3min sank=01:00:20 crit=00:23:59 rashi=12 */
    {1900,  9, 17, SOLAR_CAL_BENGALI,      6, 1, 1307},  /* delta=+36.7min sank=01:00:39 crit=00:23:59 rashi=6 */
    {1902, 10, 18, SOLAR_CAL_BENGALI,      7, 1, 1309},  /* delta=+38.9min sank=01:02:52 crit=00:23:59 rashi=7 */
    {1956,  7, 17, SOLAR_CAL_BENGALI,      4, 1, 1363},  /* delta=+38.9min sank=01:02:52 crit=00:23:59 rashi=4 */
    {2028,  6, 16, SOLAR_CAL_BENGALI,      3, 1, 1435},  /* delta=+43.5min sank=01:07:31 crit=00:23:59 rashi=3 */
    {1941, 10, 18, SOLAR_CAL_BENGALI,      7, 1, 1348},  /* delta=+43.6min sank=01:07:35 crit=00:23:59 rashi=7 */
    {1900,  8, 17, SOLAR_CAL_BENGALI,      5, 1, 1307},  /* delta=+44.4min sank=01:08:22 crit=00:23:59 rashi=5 */
    {2019, 10, 19, SOLAR_CAL_BENGALI,      7, 1, 1426},  /* delta=+46.2min sank=01:10:09 crit=00:23:59 rashi=7 */
    {2005, 12, 17, SOLAR_CAL_BENGALI,      9, 1, 1412},  /* delta=+46.6min sank=01:10:33 crit=00:23:59 rashi=9 */
    {1989,  6, 16, SOLAR_CAL_BENGALI,      3, 1, 1396},  /* delta=+47.9min sank=01:11:56 crit=00:23:59 rashi=3 */
    {1938,  1, 15, SOLAR_CAL_BENGALI,     10, 1, 1344},  /* delta=+50.2min sank=01:14:11 crit=00:23:59 rashi=10 */
    {2033,  5, 16, SOLAR_CAL_BENGALI,      2, 1, 1440},  /* delta=+50.2min sank=01:14:13 crit=00:23:59 rashi=2 */
    {2044, 12, 17, SOLAR_CAL_BENGALI,      9, 1, 1451},  /* delta=+50.7min sank=01:14:42 crit=00:23:59 rashi=9 */
    {1917,  7, 17, SOLAR_CAL_BENGALI,      4, 1, 1324},  /* delta=+51.7min sank=01:15:43 crit=00:23:59 rashi=4 */
    {1966, 12, 17, SOLAR_CAL_BENGALI,      9, 1, 1373},  /* delta=+52.4min sank=01:16:24 crit=00:23:59 rashi=9 */
    {1974,  4, 15, SOLAR_CAL_BENGALI,      1, 1, 1381},  /* delta=+52.8min sank=01:16:46 crit=00:23:59 rashi=1 */
    {1913,  3, 15, SOLAR_CAL_BENGALI,     12, 1, 1319},  /* delta=+54.0min sank=01:17:58 crit=00:23:59 rashi=12 */
    {1935,  4, 15, SOLAR_CAL_BENGALI,      1, 1, 1342},  /* delta=+54.0min sank=01:18:01 crit=00:23:59 rashi=1 */

    /* ---- ODIA - 100 closest to 22:12 IST ---- */
    {1907, 12, 16, SOLAR_CAL_ODIA,         9, 1, 1829},  /* delta=+0.4min sank=22:12:24 crit=22:11:59 rashi=9 */
    {2024, 12, 15, SOLAR_CAL_ODIA,         9, 1, 1946},  /* delta=-0.4min sank=22:11:33 crit=22:11:59 rashi=9 */
    {1915,  4, 13, SOLAR_CAL_ODIA,         1, 1, 1837},  /* delta=-0.7min sank=22:11:18 crit=22:11:59 rashi=1 */
    {1985, 12, 15, SOLAR_CAL_ODIA,         9, 1, 1907},  /* delta=-0.9min sank=22:11:03 crit=22:11:59 rashi=9 */
    {1974,  5, 14, SOLAR_CAL_ODIA,         2, 1, 1896},  /* delta=-2.3min sank=22:09:42 crit=22:11:59 rashi=2 */
    {1918,  1, 13, SOLAR_CAL_ODIA,        10, 1, 1839},  /* delta=-2.5min sank=22:09:30 crit=22:11:59 rashi=10 */
    {1971,  3, 15, SOLAR_CAL_ODIA,        12, 1, 1892},  /* delta=+2.6min sank=22:14:36 crit=22:11:59 rashi=12 */
    {2040,  9, 17, SOLAR_CAL_ODIA,         6, 1, 1962},  /* delta=+2.6min sank=22:14:36 crit=22:11:59 rashi=6 */
    {1957,  1, 13, SOLAR_CAL_ODIA,        10, 1, 1878},  /* delta=-2.9min sank=22:09:03 crit=22:11:59 rashi=10 */
    {1946, 12, 15, SOLAR_CAL_ODIA,         9, 1, 1868},  /* delta=-3.1min sank=22:08:53 crit=22:11:59 rashi=9 */
    {2042, 11, 17, SOLAR_CAL_ODIA,         8, 1, 1964},  /* delta=+3.2min sank=22:15:11 crit=22:11:59 rashi=8 */
    {1935,  5, 15, SOLAR_CAL_ODIA,         2, 1, 1857},  /* delta=+4.1min sank=22:16:08 crit=22:11:59 rashi=2 */
    {1912,  2, 13, SOLAR_CAL_ODIA,        11, 1, 1833},  /* delta=+4.3min sank=22:16:15 crit=22:11:59 rashi=11 */
    {2013,  5, 15, SOLAR_CAL_ODIA,         2, 1, 1935},  /* delta=+4.5min sank=22:16:31 crit=22:11:59 rashi=2 */
    {1969,  6, 15, SOLAR_CAL_ODIA,         3, 1, 1891},  /* delta=+5.7min sank=22:17:39 crit=22:11:59 rashi=3 */
    {2032,  4, 13, SOLAR_CAL_ODIA,         1, 1, 1954},  /* delta=-5.8min sank=22:06:10 crit=22:11:59 rashi=1 */
    {1993,  4, 14, SOLAR_CAL_ODIA,         1, 1, 1915},  /* delta=+5.9min sank=22:17:56 crit=22:11:59 rashi=1 */
    {2001,  9, 17, SOLAR_CAL_ODIA,         6, 1, 1923},  /* delta=+6.3min sank=22:18:16 crit=22:11:59 rashi=6 */
    {1936,  7, 15, SOLAR_CAL_ODIA,         4, 1, 1858},  /* delta=-6.7min sank=22:05:19 crit=22:11:59 rashi=4 */
    {2040,  8, 17, SOLAR_CAL_ODIA,         5, 1, 1962},  /* delta=+6.7min sank=22:18:43 crit=22:11:59 rashi=5 */
    {1960, 10, 16, SOLAR_CAL_ODIA,         7, 1, 1882},  /* delta=-6.8min sank=22:05:13 crit=22:11:59 rashi=7 */
    {1954,  4, 14, SOLAR_CAL_ODIA,         1, 1, 1876},  /* delta=+7.2min sank=22:19:09 crit=22:11:59 rashi=1 */
    {1932,  3, 14, SOLAR_CAL_ODIA,        12, 1, 1853},  /* delta=+7.3min sank=22:19:16 crit=22:11:59 rashi=12 */
    {1996,  1, 15, SOLAR_CAL_ODIA,        10, 1, 1917},  /* delta=+8.6min sank=22:20:37 crit=22:11:59 rashi=10 */
    {1964, 11, 16, SOLAR_CAL_ODIA,         8, 1, 1886},  /* delta=+8.9min sank=22:20:55 crit=22:11:59 rashi=8 */
    {2029,  2, 13, SOLAR_CAL_ODIA,        11, 1, 1950},  /* delta=+9.4min sank=22:21:26 crit=22:11:59 rashi=11 */
    {2010,  3, 15, SOLAR_CAL_ODIA,        12, 1, 1931},  /* delta=+10.9min sank=22:22:54 crit=22:11:59 rashi=12 */
    {2049,  3, 15, SOLAR_CAL_ODIA,        12, 1, 1970},  /* delta=+11.4min sank=22:23:21 crit=22:11:59 rashi=12 */
    {2001,  8, 17, SOLAR_CAL_ODIA,         5, 1, 1923},  /* delta=+12.4min sank=22:24:24 crit=22:11:59 rashi=5 */
    {1951,  2, 13, SOLAR_CAL_ODIA,        11, 1, 1872},  /* delta=+12.5min sank=22:24:32 crit=22:11:59 rashi=11 */
    {1962,  9, 17, SOLAR_CAL_ODIA,         6, 1, 1884},  /* delta=+12.6min sank=22:24:37 crit=22:11:59 rashi=6 */
    {2008,  6, 14, SOLAR_CAL_ODIA,         3, 1, 1930},  /* delta=-13.5min sank=21:58:28 crit=22:11:59 rashi=3 */
    {2042, 10, 18, SOLAR_CAL_ODIA,         7, 1, 1964},  /* delta=+13.7min sank=22:25:43 crit=22:11:59 rashi=7 */
    {2003, 11, 17, SOLAR_CAL_ODIA,         8, 1, 1925},  /* delta=+13.7min sank=22:25:44 crit=22:11:59 rashi=8 */
    {1990,  2, 13, SOLAR_CAL_ODIA,        11, 1, 1911},  /* delta=+14.3min sank=22:26:20 crit=22:11:59 rashi=11 */
    {1999, 10, 17, SOLAR_CAL_ODIA,         7, 1, 1921},  /* delta=-15.0min sank=21:56:58 crit=22:11:59 rashi=7 */
    {2025,  2, 12, SOLAR_CAL_ODIA,        11, 1, 1946},  /* delta=-16.5min sank=21:55:27 crit=22:11:59 rashi=11 */
    {1925, 11, 16, SOLAR_CAL_ODIA,         8, 1, 1847},  /* delta=+16.6min sank=22:28:36 crit=22:11:59 rashi=8 */
    {2035,  1, 15, SOLAR_CAL_ODIA,        10, 1, 1956},  /* delta=+17.2min sank=22:29:14 crit=22:11:59 rashi=10 */
    {2038, 10, 17, SOLAR_CAL_ODIA,         7, 1, 1960},  /* delta=-17.6min sank=21:54:23 crit=22:11:59 rashi=7 */
    {1967,  3, 14, SOLAR_CAL_ODIA,        12, 1, 1888},  /* delta=-18.0min sank=21:54:02 crit=22:11:59 rashi=12 */
    {1921, 10, 16, SOLAR_CAL_ODIA,         7, 1, 1843},  /* delta=-18.0min sank=21:53:57 crit=22:11:59 rashi=7 */
    {1930,  6, 15, SOLAR_CAL_ODIA,         3, 1, 1852},  /* delta=+18.2min sank=22:30:10 crit=22:11:59 rashi=3 */
    {1919,  8, 16, SOLAR_CAL_ODIA,         5, 1, 1841},  /* delta=-18.5min sank=21:53:31 crit=22:11:59 rashi=5 */
    {1962,  8, 17, SOLAR_CAL_ODIA,         5, 1, 1884},  /* delta=+18.5min sank=22:30:31 crit=22:11:59 rashi=5 */
    {1923,  9, 17, SOLAR_CAL_ODIA,         6, 1, 1845},  /* delta=+19.1min sank=22:31:06 crit=22:11:59 rashi=6 */
    {1928,  3, 13, SOLAR_CAL_ODIA,        12, 1, 1849},  /* delta=-19.1min sank=21:52:52 crit=22:11:59 rashi=12 */
    {1986,  2, 12, SOLAR_CAL_ODIA,        11, 1, 1907},  /* delta=-19.8min sank=21:52:14 crit=22:11:59 rashi=11 */
    {2018,  7, 17, SOLAR_CAL_ODIA,         4, 1, 1940},  /* delta=+20.4min sank=22:32:24 crit=22:11:59 rashi=4 */
    {2047,  6, 15, SOLAR_CAL_ODIA,         3, 1, 1969},  /* delta=-21.7min sank=21:50:17 crit=22:11:59 rashi=3 */
    {1931,  5, 14, SOLAR_CAL_ODIA,         2, 1, 1853},  /* delta=-21.7min sank=21:50:15 crit=22:11:59 rashi=2 */
    {1911,  4, 13, SOLAR_CAL_ODIA,         1, 1, 1833},  /* delta=-22.0min sank=21:50:00 crit=22:11:59 rashi=1 */
    {2006,  3, 14, SOLAR_CAL_ODIA,        12, 1, 1927},  /* delta=-22.4min sank=21:49:35 crit=22:11:59 rashi=12 */
    {2028, 12, 16, SOLAR_CAL_ODIA,         9, 1, 1950},  /* delta=+22.4min sank=22:34:24 crit=22:11:59 rashi=9 */
    {2014,  7, 16, SOLAR_CAL_ODIA,         4, 1, 1936},  /* delta=-22.4min sank=21:49:34 crit=22:11:59 rashi=4 */
    {1947,  2, 12, SOLAR_CAL_ODIA,        11, 1, 1868},  /* delta=-22.5min sank=21:49:32 crit=22:11:59 rashi=11 */
    {1965,  6, 14, SOLAR_CAL_ODIA,         3, 1, 1887},  /* delta=-23.0min sank=21:48:59 crit=22:11:59 rashi=3 */
    {1908,  2, 12, SOLAR_CAL_ODIA,        11, 1, 1829},  /* delta=-23.5min sank=21:48:30 crit=22:11:59 rashi=11 */
    {1960, 11, 15, SOLAR_CAL_ODIA,         8, 1, 1882},  /* delta=-24.0min sank=21:48:01 crit=22:11:59 rashi=8 */
    {2038, 11, 16, SOLAR_CAL_ODIA,         8, 1, 1960},  /* delta=-24.1min sank=21:47:56 crit=22:11:59 rashi=8 */
    {1923,  8, 17, SOLAR_CAL_ODIA,         5, 1, 1845},  /* delta=+25.0min sank=22:36:59 crit=22:11:59 rashi=5 */
    {2045,  3, 14, SOLAR_CAL_ODIA,        12, 1, 1966},  /* delta=-25.1min sank=21:46:53 crit=22:11:59 rashi=12 */
    {2003, 10, 18, SOLAR_CAL_ODIA,         7, 1, 1925},  /* delta=+25.6min sank=22:37:36 crit=22:11:59 rashi=7 */
    {1964, 10, 17, SOLAR_CAL_ODIA,         7, 1, 1886},  /* delta=+26.1min sank=22:38:04 crit=22:11:59 rashi=7 */
    {1997,  8, 16, SOLAR_CAL_ODIA,         5, 1, 1919},  /* delta=-26.1min sank=21:45:54 crit=22:11:59 rashi=5 */
    {1940,  7, 16, SOLAR_CAL_ODIA,         4, 1, 1862},  /* delta=+26.4min sank=22:38:22 crit=22:11:59 rashi=4 */
    {1919,  9, 16, SOLAR_CAL_ODIA,         6, 1, 1841},  /* delta=-26.6min sank=21:45:22 crit=22:11:59 rashi=6 */
    {2031,  1, 14, SOLAR_CAL_ODIA,        10, 1, 1952},  /* delta=-26.7min sank=21:45:20 crit=22:11:59 rashi=10 */
    {2012,  6, 15, SOLAR_CAL_ODIA,         3, 1, 1934},  /* delta=+26.7min sank=22:38:43 crit=22:11:59 rashi=3 */
    {1975,  7, 16, SOLAR_CAL_ODIA,         4, 1, 1897},  /* delta=-27.2min sank=21:44:47 crit=22:11:59 rashi=4 */
    {1999, 11, 16, SOLAR_CAL_ODIA,         8, 1, 1921},  /* delta=-28.2min sank=21:43:45 crit=22:11:59 rashi=8 */
    {1958,  8, 16, SOLAR_CAL_ODIA,         5, 1, 1880},  /* delta=-28.3min sank=21:43:44 crit=22:11:59 rashi=5 */
    {1911, 12, 16, SOLAR_CAL_ODIA,         9, 1, 1833},  /* delta=+28.3min sank=22:40:18 crit=22:11:59 rashi=9 */
    {1950,  4, 13, SOLAR_CAL_ODIA,         1, 1, 1872},  /* delta=-28.6min sank=21:43:25 crit=22:11:59 rashi=1 */
    {1979,  7, 17, SOLAR_CAL_ODIA,         4, 1, 1901},  /* delta=+29.1min sank=22:41:07 crit=22:11:59 rashi=4 */
    {1926,  6, 14, SOLAR_CAL_ODIA,         3, 1, 1848},  /* delta=-29.4min sank=21:42:36 crit=22:11:59 rashi=3 */
    {1973,  6, 15, SOLAR_CAL_ODIA,         3, 1, 1895},  /* delta=+29.5min sank=22:41:27 crit=22:11:59 rashi=3 */
    {1997,  9, 16, SOLAR_CAL_ODIA,         6, 1, 1919},  /* delta=-30.1min sank=21:41:56 crit=22:11:59 rashi=6 */
    {1989,  4, 13, SOLAR_CAL_ODIA,         1, 1, 1911},  /* delta=-30.4min sank=21:41:37 crit=22:11:59 rashi=1 */
    {1970,  5, 14, SOLAR_CAL_ODIA,         2, 1, 1892},  /* delta=-30.4min sank=21:41:35 crit=22:11:59 rashi=2 */
    {1989, 12, 16, SOLAR_CAL_ODIA,         9, 1, 1911},  /* delta=+31.1min sank=22:43:03 crit=22:11:59 rashi=9 */
    {1950, 12, 16, SOLAR_CAL_ODIA,         9, 1, 1872},  /* delta=+31.7min sank=22:43:39 crit=22:11:59 rashi=9 */
    {1953,  1, 13, SOLAR_CAL_ODIA,        10, 1, 1874},  /* delta=-32.4min sank=21:39:36 crit=22:11:59 rashi=10 */
    {2036,  8, 16, SOLAR_CAL_ODIA,         5, 1, 1958},  /* delta=-32.6min sank=21:39:24 crit=22:11:59 rashi=5 */
    {2020, 12, 15, SOLAR_CAL_ODIA,         9, 1, 1942},  /* delta=-33.0min sank=21:38:57 crit=22:11:59 rashi=9 */
    {2044,  9, 17, SOLAR_CAL_ODIA,         6, 1, 1966},  /* delta=+33.1min sank=22:45:04 crit=22:11:59 rashi=6 */
    {2028,  4, 13, SOLAR_CAL_ODIA,         1, 1, 1950},  /* delta=-33.5min sank=21:38:27 crit=22:11:59 rashi=1 */
    {2004,  6, 14, SOLAR_CAL_ODIA,         3, 1, 1926},  /* delta=-34.1min sank=21:37:55 crit=22:11:59 rashi=3 */
    {1936,  3, 14, SOLAR_CAL_ODIA,        12, 1, 1857},  /* delta=+34.7min sank=22:46:43 crit=22:11:59 rashi=12 */
    {1958,  9, 16, SOLAR_CAL_ODIA,         6, 1, 1880},  /* delta=-34.8min sank=21:37:13 crit=22:11:59 rashi=6 */
    {1922,  1, 14, SOLAR_CAL_ODIA,        10, 1, 1843},  /* delta=+35.2min sank=22:47:11 crit=22:11:59 rashi=10 */
    {2036,  9, 16, SOLAR_CAL_ODIA,         6, 1, 1958},  /* delta=-35.6min sank=21:36:21 crit=22:11:59 rashi=6 */
    {2044,  8, 17, SOLAR_CAL_ODIA,         5, 1, 1966},  /* delta=+36.2min sank=22:48:12 crit=22:11:59 rashi=5 */
    {1925, 10, 17, SOLAR_CAL_ODIA,         7, 1, 1847},  /* delta=+36.4min sank=22:48:22 crit=22:11:59 rashi=7 */
    {1992,  1, 14, SOLAR_CAL_ODIA,        10, 1, 1913},  /* delta=-36.5min sank=21:35:31 crit=22:11:59 rashi=10 */
    {1939,  5, 15, SOLAR_CAL_ODIA,         2, 1, 1861},  /* delta=+36.9min sank=22:48:51 crit=22:11:59 rashi=2 */
    {1914,  1, 13, SOLAR_CAL_ODIA,        10, 1, 1835},  /* delta=-37.1min sank=21:34:51 crit=22:11:59 rashi=10 */
    {2007, 11, 17, SOLAR_CAL_ODIA,         8, 1, 1929},  /* delta=+37.2min sank=22:49:10 crit=22:11:59 rashi=8 */
    {2009,  5, 14, SOLAR_CAL_ODIA,         2, 1, 1931},  /* delta=-37.2min sank=21:34:46 crit=22:11:59 rashi=2 */
    {1981, 12, 15, SOLAR_CAL_ODIA,         9, 1, 1903},  /* delta=-37.3min sank=21:34:44 crit=22:11:59 rashi=9 */

    /* ---- MALAYALAM - 100 closest to end of madhyahna ---- */
    {1913,  6, 14, SOLAR_CAL_MALAYALAM,   10, 32, 1088},  /* delta=-0.0min sank=13:44:30 crit=13:44:33 rashi=3 CORRECTED */
    {1954,  3, 15, SOLAR_CAL_MALAYALAM,    8, 1, 1129},  /* delta=+0.3min sank=13:42:26 crit=13:42:10 rashi=12 */
    {2021, 11, 16, SOLAR_CAL_MALAYALAM,    3, 30, 1197},  /* delta=-0.3min sank=13:09:32 crit=13:09:49 rashi=8 CORRECTED */
    {1982, 11, 16, SOLAR_CAL_MALAYALAM,    3, 30, 1158},  /* delta=-0.8min sank=13:09:00 crit=13:09:50 rashi=8 CORRECTED */
    {1943, 11, 16, SOLAR_CAL_MALAYALAM,    3, 30, 1119},  /* delta=-1.2min sank=13:08:40 crit=13:09:52 rashi=8 CORRECTED */
    {1976,  4, 13, SOLAR_CAL_MALAYALAM,    8, 31, 1151},  /* delta=-1.2min sank=13:37:16 crit=13:38:29 rashi=1 CORRECTED */
    {1934,  2, 12, SOLAR_CAL_MALAYALAM,    6, 30, 1109},  /* delta=-1.4min sank=13:40:42 crit=13:42:05 rashi=11 CORRECTED */
    {1996,  5, 14, SOLAR_CAL_MALAYALAM,    9, 31, 1171},  /* delta=-1.5min sank=13:37:13 crit=13:38:45 rashi=2 CORRECTED */
    {1993,  3, 15, SOLAR_CAL_MALAYALAM,    8, 1, 1168},  /* delta=+2.8min sank=13:44:52 crit=13:42:05 rashi=12 */
    {1904, 11, 15, SOLAR_CAL_MALAYALAM,    3, 30, 1080},  /* delta=-3.9min sank=13:05:57 crit=13:09:53 rashi=8 CORRECTED */
    {1957,  5, 15, SOLAR_CAL_MALAYALAM,   10, 1, 1132},  /* delta=+4.0min sank=13:42:36 crit=13:38:37 rashi=2 */
    {2021, 10, 18, SOLAR_CAL_MALAYALAM,    3, 1, 1197},  /* delta=+4.2min sank=13:18:54 crit=13:14:44 rashi=7 */
    {1915,  3, 14, SOLAR_CAL_MALAYALAM,    7, 30, 1090},  /* delta=-4.7min sank=13:37:37 crit=13:42:17 rashi=12 CORRECTED */
    {2023,  9, 18, SOLAR_CAL_MALAYALAM,    2, 1, 1199},  /* delta=+4.9min sank=13:34:02 crit=13:29:10 rashi=6 */
    {1901,  1, 13, SOLAR_CAL_MALAYALAM,    5, 30, 1076},  /* delta=-5.0min sank=13:27:34 crit=13:32:34 rashi=10 CORRECTED */
    {2040,  7, 17, SOLAR_CAL_MALAYALAM,   12, 1, 1215},  /* delta=+5.2min sank=13:54:48 crit=13:49:36 rashi=4 */
    {2032,  3, 14, SOLAR_CAL_MALAYALAM,    7, 30, 1207},  /* delta=-5.5min sank=13:36:29 crit=13:42:01 rashi=12 CORRECTED */
    {2007, 12, 17, SOLAR_CAL_MALAYALAM,    5, 1, 1183},  /* delta=+6.2min sank=13:24:27 crit=13:18:15 rashi=9 */
    {1937,  4, 13, SOLAR_CAL_MALAYALAM,    8, 31, 1112},  /* delta=-6.2min sank=13:32:18 crit=13:38:32 rashi=1 CORRECTED */
    {1918,  5, 15, SOLAR_CAL_MALAYALAM,   10, 1, 1093},  /* delta=+6.4min sank=13:44:52 crit=13:38:30 rashi=2 */
    {2051,  2, 14, SOLAR_CAL_MALAYALAM,    7, 1, 1226},  /* delta=+7.6min sank=13:49:39 crit=13:42:05 rashi=11 */
    {2015,  4, 15, SOLAR_CAL_MALAYALAM,    9, 1, 1190},  /* delta=+7.7min sank=13:46:10 crit=13:38:26 rashi=1 */
    {2023,  8, 17, SOLAR_CAL_MALAYALAM,   12, 32, 1198},  /* delta=-8.4min sank=13:35:19 crit=13:43:43 rashi=5 CORRECTED */
    {1973,  2, 12, SOLAR_CAL_MALAYALAM,    6, 30, 1148},  /* delta=-9.1min sank=13:33:01 crit=13:42:06 rashi=11 CORRECTED */
    {2012,  2, 14, SOLAR_CAL_MALAYALAM,    7, 1, 1187},  /* delta=+9.2min sank=13:51:16 crit=13:42:04 rashi=11 */
    {1952,  6, 14, SOLAR_CAL_MALAYALAM,   10, 32, 1127},  /* delta=-9.3min sank=13:35:28 crit=13:44:46 rashi=3 CORRECTED */
    {1940,  1, 15, SOLAR_CAL_MALAYALAM,    6, 1, 1115},  /* delta=+9.4min sank=13:42:04 crit=13:32:42 rashi=10 */
    {1982, 10, 18, SOLAR_CAL_MALAYALAM,    3, 1, 1158},  /* delta=+9.4min sank=13:24:21 crit=13:14:57 rashi=7 */
    {1943, 10, 18, SOLAR_CAL_MALAYALAM,    3, 1, 1119},  /* delta=+9.7min sank=13:24:52 crit=13:15:10 rashi=7 */
    {1929, 12, 16, SOLAR_CAL_MALAYALAM,    5, 1, 1105},  /* delta=+9.7min sank=13:27:37 crit=13:17:55 rashi=9 */
    {2035,  5, 15, SOLAR_CAL_MALAYALAM,   10, 1, 1210},  /* delta=-10.0min sank=13:28:56 crit=13:38:54 rashi=2 */
    {1904, 10, 17, SOLAR_CAL_MALAYALAM,    3, 1, 1080},  /* delta=+12.2min sank=13:27:35 crit=13:15:23 rashi=7 */
    {1968, 12, 16, SOLAR_CAL_MALAYALAM,    5, 1, 1144},  /* delta=+13.1min sank=13:31:10 crit=13:18:04 rashi=9 */
    {2034,  6, 16, SOLAR_CAL_MALAYALAM,   11, 1, 1209},  /* delta=+13.1min sank=13:58:21 crit=13:45:13 rashi=3 */
    {1979,  1, 15, SOLAR_CAL_MALAYALAM,    6, 1, 1154},  /* delta=+13.7min sank=13:46:31 crit=13:32:52 rashi=10 */
    {2003, 12, 16, SOLAR_CAL_MALAYALAM,    5, 1, 1179},  /* delta=-14.1min sank=13:04:08 crit=13:18:13 rashi=9 */
    {1941,  9, 16, SOLAR_CAL_MALAYALAM,    2, 1, 1117},  /* delta=-14.5min sank=13:15:11 crit=13:29:41 rashi=6 */
    {2001,  7, 17, SOLAR_CAL_MALAYALAM,   12, 1, 1176},  /* delta=+14.7min sank=14:04:12 crit=13:49:31 rashi=4 */
    {1945,  8, 17, SOLAR_CAL_MALAYALAM,    1, 1, 1121},  /* delta=+14.9min sank=13:58:53 crit=13:43:59 rashi=5 */
    {1984,  8, 17, SOLAR_CAL_MALAYALAM,    1, 1, 1160},  /* delta=+14.9min sank=13:58:44 crit=13:43:50 rashi=5 */
    {1995,  6, 16, SOLAR_CAL_MALAYALAM,   11, 1, 1170},  /* delta=+15.9min sank=14:00:53 crit=13:45:00 rashi=3 */
    {2046, 12, 17, SOLAR_CAL_MALAYALAM,    5, 1, 1222},  /* delta=+16.2min sank=13:34:38 crit=13:18:24 rashi=9 */
    {1962,  7, 17, SOLAR_CAL_MALAYALAM,   12, 1, 1137},  /* delta=+17.6min sank=14:07:00 crit=13:49:27 rashi=4 */
    {2018,  1, 15, SOLAR_CAL_MALAYALAM,    6, 1, 1193},  /* delta=+17.9min sank=13:50:55 crit=13:33:02 rashi=10 */
    {1919,  7, 16, SOLAR_CAL_MALAYALAM,   12, 1, 1094},  /* delta=-18.2min sank=13:31:11 crit=13:49:20 rashi=4 */
    {1925, 12, 15, SOLAR_CAL_MALAYALAM,    5, 1, 1101},  /* delta=-18.6min sank=12:59:16 crit=13:17:54 rashi=9 */
    {1945,  9, 17, SOLAR_CAL_MALAYALAM,    2, 1, 1121},  /* delta=+18.6min sank=13:48:20 crit=13:29:42 rashi=6 */
    {1902,  9, 16, SOLAR_CAL_MALAYALAM,    2, 1, 1078},  /* delta=-19.4min sank=13:10:35 crit=13:29:58 rashi=6 */
    {2019,  9, 17, SOLAR_CAL_MALAYALAM,    2, 1, 1195},  /* delta=-19.6min sank=13:09:30 crit=13:29:09 rashi=6 */
    {1909,  6, 14, SOLAR_CAL_MALAYALAM,   11, 1, 1084},  /* delta=-21.0min sank=13:23:29 crit=13:44:31 rashi=3 */
    {1991,  6, 15, SOLAR_CAL_MALAYALAM,   11, 1, 1166},  /* delta=-21.4min sank=13:23:32 crit=13:44:59 rashi=3 */
    {1923,  7, 17, SOLAR_CAL_MALAYALAM,   12, 1, 1098},  /* delta=+21.6min sank=14:10:55 crit=13:49:21 rashi=4 */
    {2047,  2, 13, SOLAR_CAL_MALAYALAM,    7, 1, 1222},  /* delta=-21.6min sank=13:20:26 crit=13:42:04 rashi=11 */
    {1980,  9, 16, SOLAR_CAL_MALAYALAM,    2, 1, 1156},  /* delta=-21.9min sank=13:07:35 crit=13:29:26 rashi=6 */
    {1941,  8, 16, SOLAR_CAL_MALAYALAM,    1, 1, 1117},  /* delta=-22.1min sank=13:21:53 crit=13:43:58 rashi=5 */
    {1956,  6, 15, SOLAR_CAL_MALAYALAM,   11, 1, 1131},  /* delta=+22.4min sank=14:07:13 crit=13:44:47 rashi=3 */
    {1964, 12, 15, SOLAR_CAL_MALAYALAM,    5, 1, 1140},  /* delta=-23.0min sank=12:55:07 crit=13:18:05 rashi=9 */
    {2027,  8, 18, SOLAR_CAL_MALAYALAM,    1, 1, 1203},  /* delta=+24.2min sank=14:07:52 crit=13:43:42 rashi=5 */
    {2014,  1, 14, SOLAR_CAL_MALAYALAM,    6, 1, 1189},  /* delta=-24.4min sank=13:08:36 crit=13:33:01 rashi=10 */
    {2042, 12, 16, SOLAR_CAL_MALAYALAM,    5, 1, 1218},  /* delta=-25.0min sank=12:53:27 crit=13:18:25 rashi=9 */
    {1975,  1, 14, SOLAR_CAL_MALAYALAM,    6, 1, 1150},  /* delta=-25.5min sank=13:07:20 crit=13:32:51 rashi=10 */
    {1914,  5, 14, SOLAR_CAL_MALAYALAM,   10, 1, 1089},  /* delta=-25.6min sank=13:12:55 crit=13:38:30 rashi=2 */
    {1906,  8, 17, SOLAR_CAL_MALAYALAM,    1, 1, 1082},  /* delta=+25.9min sank=14:10:02 crit=13:44:06 rashi=5 */
    {1902,  8, 16, SOLAR_CAL_MALAYALAM,    1, 1, 1078},  /* delta=-26.0min sank=13:18:06 crit=13:44:08 rashi=5 */
    {1984,  9, 17, SOLAR_CAL_MALAYALAM,    2, 1, 1160},  /* delta=+26.5min sank=13:55:53 crit=13:29:24 rashi=6 */
    {2025, 11, 17, SOLAR_CAL_MALAYALAM,    4, 1, 1201},  /* delta=+26.6min sank=13:36:24 crit=13:09:49 rashi=8 */
    {1900, 10, 16, SOLAR_CAL_MALAYALAM,    3, 1, 1076},  /* delta=-26.7min sank=12:48:43 crit=13:15:22 rashi=7 */
    {1980,  8, 16, SOLAR_CAL_MALAYALAM,    1, 1, 1156},  /* delta=-27.9min sank=13:15:54 crit=13:43:50 rashi=5 */
    {1997,  7, 16, SOLAR_CAL_MALAYALAM,   12, 1, 1172},  /* delta=-28.1min sank=13:21:23 crit=13:49:31 rashi=4 */
    {1958,  7, 16, SOLAR_CAL_MALAYALAM,   12, 1, 1133},  /* delta=-28.6min sank=13:20:52 crit=13:49:26 rashi=4 */
    {1906,  9, 17, SOLAR_CAL_MALAYALAM,    2, 1, 1082},  /* delta=+29.6min sank=13:59:34 crit=13:29:56 rashi=6 */
    {1969,  2, 12, SOLAR_CAL_MALAYALAM,    7, 1, 1144},  /* delta=-29.7min sank=13:12:24 crit=13:42:05 rashi=11 */
    {1911,  3, 14, SOLAR_CAL_MALAYALAM,    8, 1, 1086},  /* delta=-29.8min sank=13:12:28 crit=13:42:17 rashi=12 */
    {1930,  2, 12, SOLAR_CAL_MALAYALAM,    7, 1, 1105},  /* delta=-30.0min sank=13:12:07 crit=13:42:05 rashi=11 */
    {2030,  6, 15, SOLAR_CAL_MALAYALAM,   11, 1, 1205},  /* delta=-30.1min sank=13:15:07 crit=13:45:12 rashi=3 */
    {1938,  2, 13, SOLAR_CAL_MALAYALAM,    7, 1, 1113},  /* delta=+30.2min sank=14:12:18 crit=13:42:05 rashi=11 */
    {2025, 10, 18, SOLAR_CAL_MALAYALAM,    3, 1, 1201},  /* delta=+30.3min sank=13:45:00 crit=13:14:44 rashi=7 */
    {1933,  4, 13, SOLAR_CAL_MALAYALAM,    9, 1, 1108},  /* delta=-31.0min sank=13:07:29 crit=13:38:31 rashi=1 */
    {1950,  3, 14, SOLAR_CAL_MALAYALAM,    8, 1, 1125},  /* delta=-31.7min sank=13:10:28 crit=13:42:11 rashi=12 */
    {1953,  5, 14, SOLAR_CAL_MALAYALAM,   10, 1, 1128},  /* delta=-31.8min sank=13:06:48 crit=13:38:37 rashi=2 */
    {2050,  4, 14, SOLAR_CAL_MALAYALAM,    9, 1, 1225},  /* delta=-31.8min sank=13:06:33 crit=13:38:23 rashi=1 */
    {1988,  8, 17, SOLAR_CAL_MALAYALAM,    1, 1, 1164},  /* delta=+32.6min sank=14:16:27 crit=13:43:51 rashi=5 */
    {2028,  3, 14, SOLAR_CAL_MALAYALAM,    8, 1, 1203},  /* delta=-33.0min sank=13:09:02 crit=13:42:00 rashi=12 */
    {2036,  7, 16, SOLAR_CAL_MALAYALAM,   12, 1, 1211},  /* delta=-33.5min sank=13:16:05 crit=13:49:36 rashi=4 */
    {1989,  3, 14, SOLAR_CAL_MALAYALAM,    8, 1, 1164},  /* delta=-33.6min sank=13:08:27 crit=13:42:06 rashi=12 */
    {1939, 10, 17, SOLAR_CAL_MALAYALAM,    3, 1, 1115},  /* delta=-33.7min sank=12:41:30 crit=13:15:11 rashi=7 */
    {1986, 11, 17, SOLAR_CAL_MALAYALAM,    4, 1, 1162},  /* delta=+34.3min sank=13:44:05 crit=13:09:50 rashi=8 */
    {2017, 10, 17, SOLAR_CAL_MALAYALAM,    3, 1, 1193},  /* delta=-34.5min sank=12:40:17 crit=13:14:45 rashi=7 */
    {1902,  4, 14, SOLAR_CAL_MALAYALAM,    9, 1, 1077},  /* delta=+34.6min sank=14:13:10 crit=13:38:35 rashi=1 */
    {2044,  7, 17, SOLAR_CAL_MALAYALAM,   12, 1, 1219},  /* delta=+34.6min sank=14:24:13 crit=13:49:37 rashi=4 */
    {2019,  8, 17, SOLAR_CAL_MALAYALAM,    1, 1, 1195},  /* delta=-35.2min sank=13:08:27 crit=13:43:42 rashi=5 */
    {1997,  3, 15, SOLAR_CAL_MALAYALAM,    8, 1, 1172},  /* delta=+36.0min sank=14:18:07 crit=13:42:06 rashi=12 */
    {2027,  9, 18, SOLAR_CAL_MALAYALAM,    2, 1, 1203},  /* delta=+36.1min sank=14:05:11 crit=13:29:08 rashi=6 */
    {1947, 11, 17, SOLAR_CAL_MALAYALAM,    4, 1, 1123},  /* delta=+36.1min sank=13:45:56 crit=13:09:51 rashi=8 */
    {1919,  3, 15, SOLAR_CAL_MALAYALAM,    8, 1, 1094},  /* delta=+36.5min sank=14:18:46 crit=13:42:15 rashi=12 */
    {1917,  6, 15, SOLAR_CAL_MALAYALAM,   11, 1, 1092},  /* delta=+36.6min sank=14:21:11 crit=13:44:33 rashi=3 */
    {1978, 10, 17, SOLAR_CAL_MALAYALAM,    3, 1, 1154},  /* delta=-37.2min sank=12:37:49 crit=13:14:58 rashi=7 */
    {2019,  4, 15, SOLAR_CAL_MALAYALAM,    9, 1, 1194},  /* delta=+37.4min sank=14:15:54 crit=13:38:28 rashi=1 */
    {1908, 11, 16, SOLAR_CAL_MALAYALAM,    4, 1, 1084},  /* delta=+38.8min sank=13:48:40 crit=13:09:52 rashi=8 */
    {1972, 12, 16, SOLAR_CAL_MALAYALAM,    5, 1, 1148},  /* delta=+39.2min sank=13:57:20 crit=13:18:06 rashi=9 */
};

static void test_edge_cases(void)
{
    printf("\n--- Solar edge cases: boundary sankrantis ---\n");
    Location delhi = DEFAULT_LOCATION;
    int n = sizeof(edge_cases) / sizeof(edge_cases[0]);

    for (int i = 0; i < n; i++) {
        SolarDate sd = gregorian_to_solar(edge_cases[i].gy, edge_cases[i].gm,
                                          edge_cases[i].gd, &delhi,
                                          edge_cases[i].type);

        const char *cal_names[] = {"Tamil", "Bengali", "Odia", "Malayalam"};
        char buf[256];

        /* Check month */
        snprintf(buf, sizeof(buf), "%s %04d-%02d-%02d month (got %d [%s], expected %d [%s])",
                 cal_names[edge_cases[i].type],
                 edge_cases[i].gy, edge_cases[i].gm, edge_cases[i].gd,
                 sd.month, solar_month_name(sd.month, edge_cases[i].type),
                 edge_cases[i].exp_month,
                 solar_month_name(edge_cases[i].exp_month, edge_cases[i].type));
        check(sd.month == edge_cases[i].exp_month, buf);

        /* Check day */
        snprintf(buf, sizeof(buf), "%s %04d-%02d-%02d day (got %d, expected %d)",
                 cal_names[edge_cases[i].type],
                 edge_cases[i].gy, edge_cases[i].gm, edge_cases[i].gd,
                 sd.day, edge_cases[i].exp_day);
        check(sd.day == edge_cases[i].exp_day, buf);

        /* Check year */
        snprintf(buf, sizeof(buf), "%s %04d-%02d-%02d year (got %d, expected %d)",
                 cal_names[edge_cases[i].type],
                 edge_cases[i].gy, edge_cases[i].gm, edge_cases[i].gd,
                 sd.year, edge_cases[i].exp_year);
        check(sd.year == edge_cases[i].exp_year, buf);
    }
}

int main(void)
{
    astro_init(NULL);

    test_edge_cases();

    astro_close();

    printf("\n=== Solar edge: %d/%d passed, %d failed ===\n",
           tests_passed, tests_run, tests_failed);
    return (tests_failed == 0) ? 0 : 1;
}
